import {
  type User,
  type Wallet,
  type ExchangeRates,
  type Transaction,
  type Bank,
} from "./types";

export const mockUser: User = {
  id: "usr_001",
  fullName: "Alex Nguyen",
  email: "alex@beampay.io",
  phone: "+84 912 345 678",
  country: "VN",
  beamPayId: "BEAM-4829",
  createdAt: "2024-11-15T08:00:00Z",
};

export const mockWallet: Wallet = {
  balances: [
    { currency: "USD", amount: 248.96 },
    { currency: "VND", amount: 4177548.8 },
    { currency: "USDT", amount: 248.96 },
  ],
  primaryCurrency: "USD",
};

export const mockExchangeRates: ExchangeRates = {
  USDT_USD: 1.0,
  USD_VND: 25450,
  USDT_VND: 25450,
  USD_IDR: 16800,
};

export const mockTransactions: Transaction[] = [
  {
    id: "txn_001",
    type: "add_fund_stablecoin",
    direction: "incoming",
    status: "completed",
    amount: 200,
    currency: "USDT",
    convertedAmount: 200,
    convertedCurrency: "USD",
    description: "200 USDT",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
    reference: "REF-2025-001",
  },
  {
    id: "txn_002",
    type: "transfer_qr",
    direction: "outgoing",
    status: "completed",
    amount: 20,
    currency: "USD",
    description: "QR Payment",
    recipientName: "Dwi Sasetyaningtyas",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    reference: "REF-2025-002",
  },
  {
    id: "txn_003",
    type: "transfer_bank_id",
    direction: "outgoing",
    status: "completed",
    amount: 18.9,
    currency: "USD",
    description: "Bank Transfer",
    recipientName: "Arya Iwantoro",
    recipientBank: "BCA",
    recipientAccount: "****1234",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 9).toISOString(),
    reference: "REF-2025-003",
  },
  {
    id: "txn_004",
    type: "transfer_crypto",
    direction: "outgoing",
    status: "completed",
    amount: 120,
    currency: "USDT",
    description: "120 USDT",
    recipientName: "0x7a3f...e92b",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    reference: "REF-2025-004",
  },
  {
    id: "txn_005",
    type: "transfer_qr",
    direction: "outgoing",
    status: "completed",
    amount: 22.5,
    currency: "USD",
    description: "QR Payment",
    recipientName: "Budi Rendra",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    reference: "REF-2025-005",
  },
  {
    id: "txn_006",
    type: "transfer_bank_id",
    direction: "outgoing",
    status: "completed",
    amount: 25,
    currency: "USD",
    description: "Bank Transfer",
    recipientName: "Rina Melati",
    recipientBank: "BNI",
    recipientAccount: "****5678",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    reference: "REF-2025-006",
  },
  {
    id: "txn_007",
    type: "transfer_qr",
    direction: "outgoing",
    status: "completed",
    amount: 19.75,
    currency: "USD",
    description: "QR Payment",
    recipientName: "Joko Wibowo",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 56).toISOString(),
    reference: "REF-2025-007",
  },
  {
    id: "txn_008",
    type: "add_fund_stablecoin",
    direction: "incoming",
    status: "completed",
    amount: 500,
    currency: "USDT",
    convertedAmount: 500,
    convertedCurrency: "USD",
    description: "500 USDT",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    reference: "REF-2025-008",
  },
  {
    id: "txn_009",
    type: "transfer_bank_vn",
    direction: "outgoing",
    status: "completed",
    amount: 15,
    currency: "USD",
    description: "Bank Transfer",
    recipientName: "Tran Minh",
    recipientBank: "Vietcombank",
    recipientAccount: "****3456",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    reference: "REF-2025-009",
  },
  {
    id: "txn_010",
    type: "add_fund_user",
    direction: "incoming",
    status: "completed",
    amount: 50,
    currency: "USD",
    description: "From Sarah Chen",
    senderName: "Sarah Chen",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    reference: "REF-2025-010",
  },
  {
    id: "txn_011",
    type: "transfer_qr",
    direction: "outgoing",
    status: "completed",
    amount: 12.5,
    currency: "USD",
    description: "QR Payment",
    recipientName: "Le Hoang",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 144).toISOString(),
    reference: "REF-2025-011",
  },
  {
    id: "txn_012",
    type: "add_fund_stablecoin",
    direction: "incoming",
    status: "completed",
    amount: 1000,
    currency: "USDT",
    convertedAmount: 1000,
    convertedCurrency: "USD",
    description: "1000 USDT",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 200).toISOString(),
    reference: "REF-2025-012",
  },
];

export const mockBanks: Bank[] = [
  // Vietnam
  { id: "vcb", name: "Vietcombank", code: "VCB", country: "VN" },
  { id: "tcb", name: "Techcombank", code: "TCB", country: "VN" },
  { id: "vpb", name: "VPBank", code: "VPB", country: "VN" },
  { id: "mb", name: "MB Bank", code: "MB", country: "VN" },
  { id: "acb", name: "ACB", code: "ACB", country: "VN" },
  // Indonesia
  { id: "bca", name: "Bank Central Asia", code: "BCA", country: "ID" },
  { id: "mandiri", name: "Mandiri Bank", code: "MANDIRI", country: "ID" },
  { id: "citi", name: "CitiBank", code: "CITI", country: "ID" },
  { id: "bank-mandiri", name: "Bank Mandiri", code: "BANK_MANDIRI", country: "ID" },
  { id: "bca-short", name: "BCA", code: "BCA_SHORT", country: "ID" },
  { id: "bni", name: "BNI", code: "BNI", country: "ID" },
  { id: "bri", name: "BRI", code: "BRI", country: "ID" },
  { id: "maybank", name: "Maybank Indonesia", code: "MAYBANK", country: "ID" },
  { id: "panin", name: "Panin Bank", code: "PANIN", country: "ID" },
  { id: "ocbc", name: "OCBC NISP", code: "OCBC", country: "ID" },
  { id: "dana", name: "DANA", code: "DANA", country: "ID" },
  { id: "gopay", name: "GoPay", code: "GOPAY", country: "ID" },
  // Philippines
  { id: "bdo", name: "BDO Unibank", code: "BDO", country: "PH" },
  { id: "bpi", name: "Bank of the Philippine Islands", code: "BPI", country: "PH" },
  { id: "metro", name: "Metrobank", code: "METRO", country: "PH" },
  { id: "land", name: "Landbank", code: "LAND", country: "PH" },
];
